SOLDIER_EXP = 0
SOLDIER_HP = 100
SOLDIER_RECHARGE = 200
VEHICLE_HP = 200
VEHICLE_RECHARGE = 1200
OPERATOR_COUNT = 3
SOLDIER_COUNT = 4
VEHICLE_COUNT = 1
SQUAD_COUNT = 3
STRATEGIES = [
    'random',
    'weakest',
    'strongest'
]
